# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: table
# File Options
files:
  include: 'sass/**/*.s+(a|c)ss'
  ignore:
    - 'vendor/**/*.*'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
      ignore-custom-properties: true
